### PR TITLE
Rebase to fetch upstream changes

### PR DESCRIPTION
**Pull request by crobby**

### CODE REVIEW

**Comment by crobby** [comment]
I have resolved the conflicts that showed-up during the "fetch from upstream".  All of them were "good" conflicts afaict (JH related things that should be different than upstream).  I *think* that if we squash and merge this that future rebases should "just work" via the github UI.  wdyt?

**Comment by anishasthana** [comment]
Were you able to test this out?

**Comment by crobby** [comment]
> Were you able to test this out?

Not yet, but if this seems like a reasonable thing to do, I will try it out.

**Comment by crobby** [comment]
> > Were you able to test this out?
> 
> Not yet, but if this seems like a reasonable thing to do, I will try it out.

Ok, I have now tested it out. Seems to be working.

**Review by anishasthana — COMMENTED** [review]
I think this looks good. nice work on the rebase!

**Comment by crobby** [comment]
Anyone have any further thoughts on this?

**Comment by anishasthana** [comment]
I'm good with merging this if we can get another +1

**Pull request merged**
