### PR TITLE
github:  update pipeline env to use auto token and fix syntax

### PR DESCRIPTION
**Pull request by zdtsw**
To use github built-in variable, see https://docs.github.com/en/actions/security-guides/automatic-token-authentication

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s):
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Review by atheo89 — APPROVED** [review]
/lgtm

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
I get "You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request."
someone with higher permission will need to merge it if it is fine.

**Comment by harshad16** [comment]
/lgtm
/approve

thanks :100:

**Pull request merged**
