### PR TITLE
[Cherry-pick]  Change anaconda cronjob image

### PR DESCRIPTION
**Pull request by Jooho**
Signed-off-by: jooho <jlee@redhat.com>

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s):
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by anishasthana** [comment]
Has this pr also been made to main/master yet?

**Review by anishasthana — APPROVED** [review]
/lgtm

**Comment by Jooho** [comment]
> Has this pr also been made to main/master yet?

It is done with the master. Only missing part is 1.22

**Comment by Jooho** [comment]
@lucferbux could you please merge this pr?

**Comment by lucferbux** [comment]
Hi @Jooho @anishasthana , instead of cherry-picking each commit, why don't we just sync this branch with main? Just to keep track of the same git history, I was trying to look for this same commit in master but the description is different.

**Comment by anishasthana** [comment]
Yeah I think that's a great idea.

**Pull request closed without merging**
