### PR TITLE
rhoai-532 add tile for e2e tutorial

### PR DESCRIPTION
**Pull request by MelissaFlinn**
Adding a dashboard  tile for the "OpenShift AI tutorial - Fraud detection example" guide

### CODE REVIEW

**Comment by zdtsw** [comment]
@MelissaFlinn should this go ODH dashboard first?

**Review by lucferbux — CHANGES_REQUESTED** [review]

**Comment by MelissaFlinn** [comment]
@zdtsw Please clarify where in odh-dashboard? My understanding is that this is the location for my PR...

**Comment by MelissaFlinn** [comment]
@lucferbux I think I fixed the indent issue in my second commit?

**Comment by zdtsw** [comment]
> @zdtsw Please clarify where in odh-dashboard? My understanding is that this is the location for my PR...

not sure how UI is doing sync with changes, it used to be something from https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard but maybe you've skipped it and change directly here?

**Comment by andrewballantyne** [comment]
> > @zdtsw Please clarify where in odh-dashboard? My understanding is that this is the location for my PR...
> 
> not sure how UI is doing sync with changes, it used to be something from https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard but maybe you've skipped it and change directly here?

There is no such thing as https://github.com/opendatahub-io/odh-manifests anymore -- we need to close that Repository or make a note of its deprecated nature. We moved to component manifests. The holdover is RHODS manifests, which is this repo.

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
do we still need this PR, if so, should this be moved into ODH odh-dashboard repo with task https://issues.redhat.com/browse/RHOAIENG-943 closing in 2.8 ?

**Comment by MelissaFlinn** [comment]
@lucferbux I believe I fixed the indent issue - can you confirm so that this can go into 2.8? The blocking issue RHOAIENG-1601 is to be fixed in 2.8

**Comment by lucferbux** [comment]
Closing this in favor of https://github.com/opendatahub-io/odh-dashboard/pull/2550 since we have migrated the manifest folder

**Pull request closed without merging**
