### PR TITLE
[WIP] Add second tag on ImageStreams and auto populate python packages

### PR DESCRIPTION
**Pull request by atheo89**
## Description
This PR updates the ImageStreams for the pre-build image notebooks to support two versions of tags. 
The scope of the double versioning is to have a version with the latest supported packages and one more with the previous bunch of packages. To facilitate the manual update on the `opendatahub.io/notebook-python-dependencies` field, created a script to do that for us. 

**#Note:** The [notebook](https://github.com/opendatahub-io/notebooks/releases)'s releases determine the versioning of the tags. 

**#Live Build:**  quay.io/rh_ee_atheodor/rhods-operator-live-catalog:1.21.0-rhods-6041

## How has been tested
Since there are two tags on the ImageStreams, when you navigate to the Notebook Server page you should expect to see both versions under each notebook, furthermore, you may inspect the versions of the packages that are corresponding to the new updated images with the latest packages.

Screenshot from 2022-12-05 11-07-25

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-6041 https://issues.redhat.com/browse/RHODS-2751
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by atheo89** [comment]
[WIP] This feature should be available to upstream first

**Comment by lucferbux** [comment]
@atheo89 this is targeted for 1.22 right? can we rebase it so we can include it asap?

**Comment by atheo89** [comment]
> @atheo89 this is targeted for 1.22 right? can we rebase it so we can include it asap? 
It is not implemented on upstream yet, the target release is for 1.23

**Comment by lucferbux** [comment]
Ah nice, let me know if you need help to get it on upstream first, and also, we should change the target release on https://issues.redhat.com/browse/RHODS-2751 to reflect is 1.23 now!

**Comment by atheo89** [comment]
I am closing that PR from here because it should be included in the upstream first.

**Pull request closed without merging**
