### PR TITLE
WIP: Support deployment of jupyterhub user notebooks to a different namespace

### PR DESCRIPTION
**Pull request by anishasthana**
This change will allow the JupyterHub SA to create pods in the namespace we choose to deploy user notebooks in.

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Comment by anishasthana** [comment]
Before we can merge this in I need to figure out how the jupyterhub_config.py needs to be updated to take the correct target namespace in.
https://github.com/red-hat-data-services/odh-manifests/blob/master/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml#L8

**Comment by crobby** [comment]
Is there any chance that this could be of any interest upstream?

**Comment by anishasthana** [comment]
I... haven't really thought of it to be honest. @vpavlin ?

**Review by crobby — COMMENTED** [review]
Seems good, I'll test this tomorrow

**Comment by anishasthana** [comment]
This was replaced by https://github.com/red-hat-data-services/odh-manifests/pull/127

**Pull request closed without merging**
