### PR TITLE
Update manifests for new operator

### PR DESCRIPTION
**Pull request by VaishnaviHire**
- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s):
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by Jooho** [comment]
@VedantMahabaleshwarkar could you please review this? This is about monitoring part.

**Review by Jooho — COMMENTED** [review]
I only checked param.env part and it looks good to me. monitoring part will be reviewed by @VedantMahabaleshwarkar

**Comment by VaishnaviHire** [comment]
For monitoring here we just moved files from [odh-deployer](https://github.com/red-hat-data-services/odh-deployer/tree/main/monitoring)

**Review by etirelli — APPROVED** [review]
lgtm

**Review by VedantMahabaleshwarkar — APPROVED** [review]
spoke to @VaishnaviHire offline. the logic to not deploy the SRE monitoring stack for self managed now lives in the operator code itself. 
/lgtm

**Pull request merged**
