### PR TITLE
Update the image stream with the new generic data science notebook image

### PR DESCRIPTION
**Pull request by atheo89**
Updated the image stream with the new generic data science notebook image

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-5114
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by lugi0** [comment]
I've been testing the live build for this. Currently the build itself has some kind of issue where the Jupyter tile does not show up in the rhods dashboard "Enabled" page.
If I bypass the dashboard and go directly to the spawner I'm able to use the updated DS image, but I'm seeing some weird behaviour.
Specifically, when trying to use pip commands inside the code cells, I keep getting a popup in the lower right corner of the page (which suggests not using pip commands directly but rather a "Manage dependencies" feature. Also, a good 50% of the time, the pip commands (even "dumb" ones like `pip show`) will fail entirely or output an error together with the expected result.
image
image

**Comment by lugi0** [comment]
In the JL UI itself, in the notebook navbar (not sure how else to call it), I also see a new `Manage dependencies` menu/plugin, which might be the cause of these new behaviours:
image

**Review by samuelvl — APPROVED** [review]
/lgtm

**Comment by aloganat** [comment]
The smoke and sanity test job for validating this PR has more failures and the cluster got deleted after execution. So, retriggering the executions for further analysis. Will post test execution result links in jira.

**Pull request merged**
