### PR TITLE
[UPSTREAM] Added livenessProbe for jupyterhub and sidecar container (…

### PR DESCRIPTION
**Pull request by anishasthana**
…#473)

Updated image

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-1619
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Review by crobby — APPROVED** [review]

**Comment by maulikjs** [comment]
Hey @lucferbux 
With the changes around the deprecated container, are these changes still valid?

**Comment by lucferbux** [comment]
@maulikjs yeah they work as the functionality is the same, although we should consider either change or even remove the livenessProbe of the sidecar container as the new image might not have that same issues (but again the changes work and there is no problem on leave them as they are right now)

**Comment by maulikjs** [comment]
I'd say lets keep this then since we cant say for sure if the new image may or may not have the problem but if it exists this definitely solves it.

**Pull request merged**
