### PR TITLE
Update Anaconda validator to remove need for additional image

### PR DESCRIPTION
**Pull request by Xaenalt**
Hey all, as part of the pruning of non-CPAAS images, we found a way to remove anaconda-validator altogether for now

Eventually we want Anaconda to own this code, but for now this should remove the need for that additional custom image

- [O] The commits are squashed in a cohesive manner and have meaningful messages.
- [O] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [O] JIRA link(s): https://issues.redhat.com/browse/RHODS-1940
- [?] The Jira story is acked
- [X] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [O] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious) Hopefully these are immediately obvious

### CODE REVIEW

**Comment by Xaenalt** [comment]
Might not merge just yet, and would need a re-test of the functionality to make sure we did this right, but should be a net positive in either case

**Comment by Xaenalt** [comment]
@tmckayus this the right place?

**Comment by Xaenalt** [comment]
Ok, idk why it's grabbing the other commit from a minute ago, hopefully someone can fix that

**Comment by tmckayus** [comment]
@Xaenalt yes this is the right place

You proably need to rebase your fork and then force push the change again

**Comment by tmckayus** [comment]
@crobby @anishasthana so it turns out the validator image is just bash around oc, like the jupyterhub deployer.

So we jammed it in the podspec and then plan on running it on top of odh-deployer.  Voila, no validator image necessary

**Comment by Xaenalt** [comment]
Aha, there we go

**Comment by anishasthana** [comment]
@Xaenalt we'll need a new story under the existing epic unfortunately.

**Comment by Xaenalt** [comment]
Yes, I had an email out to get acks on the rest of the solution from the stakeholders, was going to hear back and then flesh out a better JIRA under that epic

**Comment by anishasthana** [comment]
Sounds good, thank you!

**Comment by tmckayus** [comment]
@Xaenalt  we should hold merging this until we have confirmation on possible notebook build changes -- the imagestream annotations call out url, quay repo.  If that stuff changes we need to update the annotations embedded in this PR.

**Comment by Xaenalt** [comment]
Currently the Thoth builds target the same repo

**Comment by tmckayus** [comment]
@Xaenalt are they pushing to the same quay repository?

**Comment by Xaenalt** [comment]
Yep

**Comment by Xaenalt** [comment]
https://github.com/red-hat-data-services/s2i-minimal-notebook-anaconda/blob/master/.aicoe-ci.yaml

**Review by crobby — APPROVED** [review]
lgtm

**Review by anishasthana — COMMENTED** [review]
Changes look good

**Pull request merged**
