### PR TITLE
Update model serving images for custom serving runtimes

### PR DESCRIPTION
**Pull request by lucferbux**
Fixes https://issues.redhat.com/browse/RHOAIENG-2057

### CODE REVIEW

**Review by heyselbi — COMMENTED** [review]
these look good! confirmed.

**Review by zdtsw — APPROVED** [review]
approve based on the comments from serving team

**Review by heyselbi — CHANGES_REQUESTED** [review]
Openvino:
quay.io/modh/openvino_model_server:2023.1-release-6f0a49f
quay.io/modh/openvino_model_server@sha256:ba7acbca6c69c4cb20c13121b82e0475661221c15c4059e52ab9abfba5ee8036

**Comment by lucferbux** [comment]
> Openvino: quay.io/modh/openvino_model_server:2023.1-release-6f0a49f quay.io/modh/openvino_model_server@sha256:ba7acbca6c69c4cb20c13121b82e0475661221c15c4059e52ab9abfba5ee8036

We've already merged that image in the release branch, im not sure if we've retriggered a rebuild, isn't that the image that we need?

**Comment by zdtsw** [comment]
@lucferbux need this merge to master?

**Comment by lucferbux** [comment]
Yes, I had this into my follow up list for monday.

cc @andrewballantyne can you do it, don't have permissions please!

**Pull request merged**
