### PR TITLE
Bump up the memory limit for traefik-proxy

### PR DESCRIPTION
**Pull request by maulikjs**
- [X] The commits are squashed in a cohesive manner and have meaningful messages.

### CODE REVIEW

**Comment by maulikjs** [comment]
We have had the container restart a couple of times due to it being OOMKilled in our internal deployment, this should take care of that problem for good.

**Comment by crobby** [comment]
@maulikjs Is there a jira for this

**Comment by maulikjs** [comment]
@crobby nope, its a trivial change so I just made it. Should I make a jira?

**Comment by crobby** [comment]
> @crobby nope, its a trivial change so I just made it. Should I make a jira?

Yeah.  Just part of standard operating procedure now......I know, I know.

**Comment by maulikjs** [comment]
Here we go: https://issues.redhat.com/browse/RHODS-1901

**Pull request merged**
