### PR TITLE
Update the image stream with the new minimal notebook image

### PR DESCRIPTION
**Pull request by atheo89**
Updated the minimal notebook image source with the new one

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-5113
- [x] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Review by samuelvl — CHANGES_REQUESTED** [review]
Tests defined in [ODS-CI framework](https://github.com/red-hat-data-services/ods-ci) are failing:

```shell
$ ./run_robot_test.sh --test-case tests/Tests/500__jupyterhub/test-minimal-image.robot 
==============================================================================
Test-Minimal-Image                                                            
==============================================================================
Open RHODS Dashboard                                                  | PASS |
------------------------------------------------------------------------------
Can Launch Jupyterhub                                                 | PASS |
------------------------------------------------------------------------------
Can Login to Jupyterhub                                               | PASS |
------------------------------------------------------------------------------
Can Spawn Notebook                                                    | PASS |
------------------------------------------------------------------------------
Can Launch Python3 Smoke Test Notebook                                | FAIL |
[0.40201256371442906, 0.8875, 0.846875, 0.875, 0.896875, 0.9116818405511811] != [0.40201256371442895, 0.8875, 0.846875, 0.875, 0.896875, 0.9116818405511811]
------------------------------------------------------------------------------
[ WARN ] Executing keyword 'Run Cell And Check Output' failed:                
'WARNING: Package(s) not found: tensorflow' does not match '2.7'
Verify Tensorflow Can Be Installed In The Minimal Python Image Via... | FAIL |
AssertionError

Also teardown failed:
Several failures occurred:

1) This command requires openldap-admin1 to be connected to the cluster (oc login ...)

2) Element 'xpath://li[contains(concat(' ',normalize-space(@class),' '),' jp-DirListing-item ')]' did not disappear in 30 seconds.

3) '"lost+found
minimal-nb-image-test
ods-ci-notebooks-main
Untitled.ipynb"' does not match '""'
------------------------------------------------------------------------------
Verify Jupyterlab Server Pods Are Spawned In A Custom Namespace ::... | PASS |
------------------------------------------------------------------------------
Test-Minimal-Image                                                    | FAIL |
Suite teardown failed:
Several failures occurred:

1) This command requires openldap-admin1 to be connected to the cluster (oc login ...)

2) Element 'xpath://li[contains(concat(' ',normalize-space(@class),' '),' jp-DirListing-item ')]' did not disappear in 30 seconds.

3) '"lost+found
minimal-nb-image-test
ods-ci-notebooks-main
Untitled.ipynb"' does not match '""'

7 tests, 0 passed, 7 failed
==============================================================================
```

and:

```shell
$ ./run_robot_test.sh --test-case tests/Tests/500__jupyterhub/plugin-verification.robot
==============================================================================
Plugin-Verification                                                           
==============================================================================
Test User Notebook Plugin in JupyterLab                               .......1. https://github.com/jupyterlab/jupyterlab-git gets status code 200
2. https://github.com/jupyterlab/jupyterlab_pygments gets status code 200
3. https://github.com/jupyter/nbdime gets status code 200
Test User Notebook Plugin in JupyterLab                               | FAIL |
Plugin mismatch Found in the mentioned images '{'s2i-minimal-notebook': ['jupyterlab_pygments', 'Defaulted container "jupyter-nb-openldap-2duser1" out of: jupyter-nb-openldap-2duser1, oauth-proxy\nPython 3.8']}'
------------------------------------------------------------------------------
Plugin-Verification                                                   | FAIL |
1 test, 0 passed, 1 failed
==============================================================================

```

This requires another iteration to identify why these tests are failing and fix the possible issues.

/hold

**Comment by lugi0** [comment]
I've tested the live build with this image on a smoke run, it had 1 failure but it seems to have been a one-off problem while spawning a server pod.
I've now started a sanity run for it here: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-sanity/840/
Checking manually I've already confirmed that the permission issue when trying to install Tensorflow has been fixed.

**Comment by lugi0** [comment]
Sanity run looks ok, I don't see any new failures caused by the prebuilt img, I think this can move forward @atheo89

**Review by samuelvl — APPROVED** [review]
/lgtm

**Pull request merged**
