### PR TITLE
Append a changing value to tags for prebuilt images

### PR DESCRIPTION
**Pull request by tmckayus**
This change appends a changing value to the imagestream tags
for generic-data-science-notebook and minimal-notebook so that
new images can be distinguished from previous.

For minimal-notebook, the values in the manifest will be updated
by the downstream build. For generic-data-science, the tag will
be updated by hand.

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2364
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

This has been tested with the instructions in https://github.com/red-hat-data-services/odh-deployer/pull/206

### CODE REVIEW

**Comment by tmckayus** [comment]
This is an analog to https://github.com/red-hat-data-services/odh-deployer/pull/199 to provide changing tags for the prebuilt images.

**Review by samuelvl — APPROVED** [review]
lgtm

**Comment by tmckayus** [comment]
@samuelvl this change requires a corresponding dockerfile change in the downstream build to replace the "rhodsversion" string (I have left one for you :) )

**Review by anishasthana — COMMENTED** [review]
/hold

This guy isn't ack'd yet, so hold off on merging

**Review by crobby — APPROVED** [review]
acked, reviewed, tested via live build/upgrade  /lgtm

**Pull request merged**
